export const defaultTheme = {
  "yellow-dark": "#C47F17",
  yellow: "#DBAC2C",
  "yellow-light": "#F1E9C9",
  "purple-dark": "#4B2995",
  purple: "#8047F8",
  "purple-light": "#EBE5F9",
  "base-title": "#272221",
  "base-subtitle": "#403937",
  "base-text": "#574F4D",
  "base-label": "#8D8686",
  "base-hover": "#D7D5D5",
  "base-button": "#E6E5E5",
  "base-input": "#EDEDED",
  "base-cart": "#F3F2F2",
  background: "#FAFAFA",
  white: "#FFFFFF",

  textStyles: {
    titleXl: {
      fontSize: "3rem",
      fontFamily: '"Baloo 2", sans-serif',
      lineHeight: "130%",
    },
    titleM: {
      fontSize: "1.5rem",
      fontFamily: '"Baloo 2", sans-serif',
      lineHeight: "130%",
      fontWeight: "extra-bold",
    },
    titleXS: {
      fontSize: "1.125rem",
      fontFamily: '"Baloo 2", sans-serif',
      lineHeight: "130%",
      fontWeight: "bold",
    },
    regularL: {
      fontSize: "1.25rem",
      fontFamily: '"Roboto", sans-serif',
      lineHeight: "130%",
      fontWeight: "normal",
    },
    regularM: {
      fontSize: "1rem",
      fontFamily: '"Roboto", sans-serif',
      lineHeight: "130%",
      fontWeight: "normal",
    },
    regularS: {
      fontSize: "0.875rem",
      fontFamily: '"Roboto", sans-serif',
      lineHeight: "130%",
    },
    textXs: {
      fontSize: "0.75rem",
      fontFamily: '"Roboto", sans-serif',
      lineHeight: "130%",
      fontWeight: "bold",
    },
    tag: {
      fontSize: "0.75rem",
      lineHeight: "130%",
      fontFamily: '"Roboto", sans-serif',
      fontWeight: "bold",
    },
    balooTitleS: {
      fontSize: "1.25rem",
      lineHeight: "130%",
      fontWeight: "bold",
      fontFamily: '"Baloo 2", sans-serif',
    },
  },
};
